als_user:
    resource: "@AlsUserBundle/Resources/config/routing.yml"
    prefix:   /

hlt_manageur:
    resource: "@HltManageurBundle/Resources/config/routing.yml"
    prefix:   /manageur

sup_test:
    resource: "@SupTestBundle/Resources/config/routing.yml"
    prefix:   /test

#import des routes du Bundle AlsPlateformBundle
als_plateform:
    resource: "@AlsPlateformBundle/Resources/config/routing.yml"
    prefix:   /plateform

#    security routes
login:
    pattern:   /login
    defaults:  { _controller: AlsUserBundle:Security:login }

login_check:
    pattern:   /login_check

logout:
    pattern:   /logout