als_plateform_home:
    path:    /{page}
    defaults:
        _controller: AlsPlateformBundle:Advert:index
        page:   1
    requirements:
        page:   \d*
    
als_plateform_view:
    path:    /advert/{id}
    defaults:  { _controller: AlsPlateformBundle:Advert:view }
    requirements:
        page:  \d+

als_plateform_view_slug:
    path:   /advert/{year}/{slug}.{_format}
    defaults:
        _controller: AlsPlateformBundle:Advert:viewSlug
        _format:      html
    requirements:
        year:   \d{4}
        format:   html|xml
    
als_plateform_add:
    path:    /add
    defaults:  { _controller: AlsPlateformBundle:Advert:add }

als_plateform_edit:
    path:    /edit/{id}
    defaults:  { _controller: AlsPlateformBundle:Advert:edit }
    requirements:
            page:  \d+

als_plateform_delete:
    path:    /delete/{id}
    defaults:  { _controller: AlsPlateformBundle:Advert:delete }
    requirements:
            page:  \d+

als_plateform_view_error:
    path:    /advertError/{id}
    defaults:  { _controller: AlsPlateformBundle:Advert:viewError }

als_plateform_redirect:
    path:   /redirect
    defaults: { _controller: AlsPlateformBundle:Advert:redirect }

als_plateform_view_json:
    path:   /json-view
    defaults: { _controller: AlsPlateformBundle:Advert:jsonView }

als_plateform_view_session:
    path:   /session
    defaults: { _controller: AlsPlateformBundle:Advert:manSession }