parameters:
    #parameter_name: value

services:
    als_plateform.antispam:
        class: Als\PlateformBundle\Antispam\AlsAntispam
        arguments: [@mailer,%locale%,50]

    als_plateform.doctrine.notification:
        class: Als\PlateformBundle\DoctrineListener\ApplicationNotification
        arguments: [@mailer]
        tags:
            - { name: doctrine.event_listener, event: postPersist }