<?php

namespace Als\PlateformBundle\Repository;

use \Doctrine\ORM\EntityRepository;
/**
 * AdvertRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AdvertRepository extends EntityRepository
{
    public function myFindAll()
    {

////        Methode 1
//        $queryBuilder1 = $this->_em->createQueryBuilder()
//            ->select('a')
//            ->from($this->_entityName, 'a',null);
//
////        Methode 2
//        $queryBuilder2 = $this->createQueryBuilder('a', null);
//
//        $query = $queryBuilder1->getQuery();
//        $query = $queryBuilder2->getQuery();
//
//        $results = $query->getResult();
//
//        return $results;
//        Tout ce qui se trouve plus haut peut etre resume ainsi...
        return $this
            ->createQueryBuilder('a', null)
            ->getQuery()
            ->getResult();
    }

    public function myFindOne($id)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.id = :id')
            ->setParameter('id', $id)
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }

    public function findByAuthorAndDate($author, $year)
    {
        $qb = $this->createQueryBuilder('a');

        $qb
            ->where('a.author = :author')
            ->setParameter('author', $author)
            ->andWhere('a.date < :year')
            ->setParameter('date', $year)
            ->orderBy('a.date', 'DESC')
        ;

        return $qb
            ->getQuery()
            ->getResult()
        ;
    }
}
